# Generated by Django 2.1.1 on 2018-09-26 07:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='customApi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('className', models.TextField(verbose_name='className')),
                ('pkgName', models.CharField(max_length=1024, verbose_name='pkgName')),
                ('version', models.CharField(max_length=1024, verbose_name='版本')),
                ('leakDetail', models.TextField(verbose_name='详细信息')),
                ('create_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
            ],
        ),
    ]
